# Generated by Django 5.0.6 on 2026-10-03 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="candidate_id_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="booking",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="booking",
            name="currency",
            field=models.CharField(default="VND", max_length=8),
        ),
        migrations.AddField(
            model_name="booking",
            name="guardian_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="booking",
            name="guardian_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="booking",
            name="hold_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("INITIATED", "Initiated"),
                    ("PAID", "Paid"),
                    ("FAILED", "Failed"),
                    ("REFUNDED", "Refunded"),
                    ("PARTIALLY_REFUNDED", "Partially Refunded"),
                ],
                default="INITIATED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="price",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="booking",
            name="reschedule_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="booking",
            name="school",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="booking",
            name="special_needs",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="teacher_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING_PAYMENT", "Pending Payment"),
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("CONFIRMED", "Confirmed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING_PAYMENT",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CandidateDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("ID_CARD", "ID Card"),
                            ("PASSPORT", "Passport"),
                            ("PHOTO", "Photo"),
                            ("BIRTH_CERTIFICATE", "Birth Certificate"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=30,
                    ),
                ),
                ("file_ref", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="bookings.booking",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("PUBLISHED", "Published")],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "mark",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("grade_awarded", models.CharField(blank=True, max_length=20)),
                ("examiner_comment", models.TextField(blank=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="bookings.booking",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.CharField(max_length=100, unique=True)),
                ("file_ref", models.CharField(blank=True, max_length=500)),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "result",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate",
                        to="bookings.examresult",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                ("currency", models.CharField(default="VND", max_length=8)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("MOCK", "Mock (dev)"),
                            ("VNPAY", "VNPay"),
                            ("MOMO", "MoMo"),
                            ("ZALOPAY", "ZaloPay"),
                            ("STRIPE", "Stripe"),
                            ("CASH", "Cash"),
                        ],
                        default="MOCK",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIATED", "Initiated"),
                            ("PAID", "Paid"),
                            ("FAILED", "Failed"),
                            ("REFUNDED", "Refunded"),
                            ("PARTIALLY_REFUNDED", "Partially Refunded"),
                        ],
                        default="INITIATED",
                        max_length=20,
                    ),
                ),
                ("provider_ref", models.CharField(blank=True, max_length=100)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                (
                    "refund_amount",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                ("is_mock", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("refunded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="bookings.booking",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
