# Generated by Django 5.0.6 on 2026-04-19 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "style",
                    models.CharField(
                        choices=[
                            ("CLASSICAL_JAZZ", "Classical & Jazz"),
                            ("ROCK_POP", "Rock & Pop"),
                            ("THEORY", "Theory of Music"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["style", "name"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade", models.PositiveSmallIntegerField()),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("duration_minutes", models.PositiveSmallIntegerField()),
                ("fee", models.DecimalField(decimal_places=0, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="courses",
                        to="catalog.instrument",
                    ),
                ),
            ],
            options={
                "ordering": ["instrument__style", "instrument__name", "grade"],
                "unique_together": {("instrument", "grade")},
            },
        ),
    ]
