# Generated by Django 5.0.6 on 2026-04-21 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instrument",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="instrument",
            unique_together={("name", "style")},
        ),
    ]
