[pytest]
DJANGO_SETTINGS_MODULE = core_service.test_settings
python_files = tests/test_*.py
python_classes = Test*
python_functions = test_*
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function
