# Generated by Django 5.0.6 on 2026-04-21 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_instrument_name_and_more"),
        ("centers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Examiner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "max_exams_per_day",
                    models.PositiveSmallIntegerField(
                        default=8,
                        help_text="Maximum number of exam slots this examiner can be assigned per day.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examiners",
                        to="centers.examcenter",
                    ),
                ),
                (
                    "specializations",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Instruments/styles this examiner is qualified to assess.",
                        related_name="examiners",
                        to="catalog.instrument",
                    ),
                ),
            ],
            options={
                "ordering": ["center", "name"],
            },
        ),
        migrations.AddField(
            model_name="examslot",
            name="examiner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="slots",
                to="centers.examiner",
            ),
        ),
        migrations.CreateModel(
            name="ExaminerUnavailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("reason", models.CharField(blank=True, max_length=300)),
                (
                    "examiner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unavailabilities",
                        to="centers.examiner",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "examiner unavailabilities",
                "ordering": ["examiner", "date_from"],
            },
        ),
    ]
