# Generated by Django 5.0.6 on 2026-10-03 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("centers", "0002_examiner_examslot_examiner_examinerunavailability"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="examiner",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="examiner_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
