# Generated by Django 5.0.6 on 2026-10-03 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("STUDENT", "Student"),
                    ("PARENT", "Parent"),
                    ("TEACHER", "Teacher"),
                    ("EXAMINER", "Examiner"),
                    ("CENTER_ADMIN", "Center Admin"),
                    ("REGIONAL_ADMIN", "Regional Admin"),
                ],
                default="STUDENT",
                max_length=20,
            ),
        ),
    ]
