# Generated by Django 5.0.6 on 2026-10-03 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0002_booking_candidate_id_number_booking_contact_email_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("EMAIL", "Email"), ("SMS", "SMS"), ("PUSH", "Push")],
                        default="EMAIL",
                        max_length=10,
                    ),
                ),
                (
                    "template",
                    models.CharField(
                        choices=[
                            ("BOOKING_CONFIRMATION", "Booking confirmation"),
                            ("PAYMENT_RECEIPT", "Payment receipt"),
                            ("EXAM_REMINDER", "Exam reminder"),
                            ("EXAMINER_ASSIGNED", "Examiner assigned"),
                            ("RESULT_PUBLISHED", "Result published"),
                        ],
                        default="BOOKING_CONFIRMATION",
                        max_length=40,
                    ),
                ),
                ("recipient", models.CharField(blank=True, max_length=200)),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("body", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                        ],
                        default="QUEUED",
                        max_length=10,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="bookings.booking",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
